name: Manual Python Script Runner

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  run-make:
    runs-on: windows-latest
    timeout-minutes: 10  # Force timeout after 10 minutes

    steps:
      # Step 1: Checkout the public repository (where the action file is)
      - name: Checkout Public Repository
        uses: actions/checkout@v3

      # Step 2: Set up Git credentials using the built-in GITHUB_TOKEN (for the public repo)
      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Checkout Private Repository using the GH_TOKEN secret (Fine-grained PAT)
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: "gmail-service/gh_acc"  # Private repository to clone
          token: ${{ secrets.GH_TOKEN }}  # Fine-grained PAT secret for authentication
          path: "gh_acc"  # Path where the private repo will be cloned

      # Step 4: Install Tesseract via Chocolatey
      - name: Install Tesseract via Chocolatey
        run: choco install tesseract -y

      # Step 5: Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow faker sqlalchemy pytesseract selenium pymysql requests mechanize pycountry country_converter

      # Step 6: Replace eng.traineddata with captcha.traineddata
      - name: Replace eng.traineddata with captcha.traineddata
        run: |
          $source = "$env:GITHUB_WORKSPACE\gh_acc\captcha.traineddata"  # Path to the file in the private repo
          $dest = "C:\Program Files\Tesseract-OCR\tessdata\eng.traineddata"
          Copy-Item -Path $source -Destination $dest -Force

      # Step 7: Run make.py from the cloned private repository
#      - name: Run make.py
#        run: cmd.exe /c python.exe gh_acc\make.py  # Running the script from the cloned private repo




      - name: Run make.py with UTF-8 Encoding
        run: |
          chcp 65001
          python gh_acc\make.py
        env:
          PYTHONIOENCODING: utf-8



