name: Manual Python Script Runner

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  run-make:
    runs-on: windows-latest
    timeout-minutes: 10  # Force timeout after 10 minutes

    steps:
      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global credential.helper store
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token for authentication

      - name: Clone Private Repository
        run: |
          git clone https://github.com/gmail-service/gh_acc.git
        env:
          GIT_ASKPASS: echo  # Prevent Git from prompting for username/password
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Token used for authentication

      - name: Install Tesseract via Chocolatey
        run: choco install tesseract -y

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow faker sqlalchemy pytesseract selenium pymysql requests

      - name: Replace eng.traineddata with captcha.traineddata
        run: |
          $source = "$env:GITHUB_WORKSPACE\gh_acc\captcha.traineddata"  # Path to the file in the private repo
          $dest = "C:\Program Files\Tesseract-OCR\tessdata\eng.traineddata"
          Copy-Item -Path $source -Destination $dest -Force

      - name: Run make.py
        run: cmd.exe /c python.exe gh_acc\make.py  # Running the script from the cloned private repo
